### ISSUE TITLE
Continuing lines of msgid wrongly added to msgctxt

### ISSUE THREAD

**Issue by stephanegigandet** [maddingue/Locale-Maketext-Lexicon-Getcontext#1]
There's a parsing bug that makes continuing lines from msgid be added to msgctxt instead.

Sample .po that triggers the error:

msgctxt "multiline_msgid"
msgid "Blabla\n"
"Blablabla"
msgstr "Pouet pouet"
"Pouet"

I'm going to submit a pull request for the fix.

**Comment by stephanegigandet** [comment]
Fixed in https://github.com/maddingue/Locale-Maketext-Lexicon-Getcontext/pull/2

**Comment by maddingue** [comment]
Thanks for finding & fixing the bug. Version 0.04 is on its way to the CPAN
» https://metacpan.org/release/SAPER/Locale-Maketext-Lexicon-Getcontext-0.04
